# Generated by Django 5.0.7 on 2024-07-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_report_added_alter_report_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
