# Generated by Django 5.0.7 on 2024-07-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_report_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='intensity',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
