# Generated by Django 5.0.7 on 2024-07-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_report_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='intensity',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
