# Generated by Django 5.0.7 on 2024-07-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_report_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='intensity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
