# Generated by Django 5.0.7 on 2024-07-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_report_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
